"""Read requirements.txt files."""

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

_AUTOGENERATED = re.compile(r"autogenerated by (pip-compile|uv)")


def is_compiled(path: Path) -> bool:
    """Return whether the requirements file is compiled or locked and must be left untouched.

    A requirements file is treated as compiled when it carries `--hash=` lines (pip requires every requirement to be
    hashed, so the file is fully locked), an autogenerated pip-compile/uv header, or a sibling `.in` source file.
    """
    contents = path.read_text()
    if "--hash=" in contents:
        return True
    if _AUTOGENERATED.search(contents):
        return True
    return (path.parent / f"{path.stem}.in").exists()
