sonar.organization=ictu
sonar.projectName=Update-time
sonar.projectKey=nl.ictu:update-time
sonar.python.coverage.reportPaths=build/unittest-coverage.xml
sonar.python.xunit.reportPath=build/xunit.xml
sonar.sources=src
sonar.tests=tests
