"""Unit tests for the requirements.txt file format, with file I/O mocked."""

import unittest
from unittest.mock import MagicMock, Mock

from update_time.file_formats import requirements_txt

from tests.update_time.helpers import mock_path


class IsCompiledTest(unittest.TestCase):
    """Unit tests for detecting compiled/locked requirements files."""

    def requirements_file(self, contents: str, *, sibling_in: bool = False) -> Mock:
        """Return a mock requirements file, optionally with a sibling .in source file present."""
        requirements_txt_file = mock_path(contents)
        requirements_txt_file.stem = "requirements"
        requirements_txt_file.parent = MagicMock()
        requirements_txt_file.parent.__truediv__.return_value = Mock(exists=Mock(return_value=sibling_in))
        return requirements_txt_file

    def test_hash_pinned(self):
        """Test that a hash-pinned (fully locked) file is compiled."""
        self.assertTrue(requirements_txt.is_compiled(self.requirements_file("flask==1.0 \\\n    --hash=sha256:abc\n")))

    def test_autogenerated_header(self):
        """Test that a pip-compile/uv autogenerated header marks the file as compiled."""
        self.assertTrue(
            requirements_txt.is_compiled(self.requirements_file("# autogenerated by pip-compile\nflask==1.0\n"))
        )

    def test_sibling_in_file(self):
        """Test that a sibling .in source file marks the file as compiled."""
        self.assertTrue(requirements_txt.is_compiled(self.requirements_file("flask==1.0\n", sibling_in=True)))

    def test_plain_requirements(self):
        """Test that a plain hand-written requirements file is not compiled."""
        self.assertFalse(requirements_txt.is_compiled(self.requirements_file("flask==1.0\n")))
