"""Test that the names the modules make public have callers outside the module defining them."""

import ast
import pathlib
import unittest
from typing import TYPE_CHECKING

from tests.update_time.helpers import module_level_assignments, project

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator

# Generated by `vulture --make-whitelist`: bare names rather than code, so what it mentions means nothing.
_GENERATED_FILES = ("tools/vulture-whitelist.py",)


def _python_files() -> list[pathlib.Path]:
    """Return the Python files the visibility check reads names and references from."""
    roots = ("src", "tests", "tools")
    files = (path for root in roots for path in pathlib.Path(root).rglob("*.py"))
    return sorted(path for path in files if path.as_posix() not in _GENERATED_FILES)


def _base_names(node: ast.ClassDef) -> Iterator[str]:
    """Yield the name of each base the class lists, without the module qualifying it."""
    for base in node.bases:
        if isinstance(base, ast.Attribute):
            yield base.attr
        elif isinstance(base, ast.Name):
            yield base.id


# The bases a framework finds by scanning rather than by importing: `unittest` discovers a test case, fixit a rule.
_DISCOVERED_BASES = ("TestCase", "LintRule")


def _discovered_classes(trees: dict[pathlib.Path, ast.Module]) -> set[str]:
    """Return the names of the classes a framework discovers: the bases it scans for, and all deriving from them.

    A test class commonly derives from another test class rather than from `unittest.TestCase` itself.
    """
    classes = [node for tree in trees.values() for node in tree.body if isinstance(node, ast.ClassDef)]
    discovered = set(_DISCOVERED_BASES)
    previously = 0
    while len(discovered) != previously:
        previously = len(discovered)
        discovered |= {node.name for node in classes if discovered.intersection(_base_names(node))}
    return discovered


def _public_constants(trees: dict[pathlib.Path, ast.Module]) -> Iterator[tuple[pathlib.Path, str]]:
    """Yield the public module-level constants each module assigns."""
    for path, tree in trees.items():
        for targets, _value in module_level_assignments(tree):
            for target in targets:
                if isinstance(target, ast.Name) and not target.id.startswith("_") and target.id.isupper():
                    yield path, target.id


# The guard a module runs its entry point behind, spelled as `ast.unparse` writes it whatever quotes the source used.
_ENTRY_POINT_GUARD = "__name__ == '__main__'"


def _entry_points(tree: ast.Module) -> Iterator[str]:
    """Yield the names the module calls from behind its entry-point guard."""
    for node in tree.body:
        if isinstance(node, ast.If) and ast.unparse(node.test) == _ENTRY_POINT_GUARD:
            for called in ast.walk(node):
                if isinstance(called, ast.Call) and isinstance(called.func, ast.Name):
                    yield called.func.id


def _public_definitions(trees: dict[pathlib.Path, ast.Module]) -> Iterator[tuple[pathlib.Path, str]]:
    """Yield the public module-level functions and classes each module defines, bar those reached without a call.

    A class a framework discovers is found by scanning the module rather than by importing it, and an entry point
    is reached by running its file, so neither has a caller to find and reporting it would buy nothing.
    """
    discovered = _discovered_classes(trees)
    for path, tree in trees.items():
        reached = discovered.union(_entry_points(tree))
        for node in tree.body:
            if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef | ast.ClassDef):
                continue
            if not node.name.startswith("_") and node.name not in reached:
                yield path, node.name


def _module_local_constants(files: list[pathlib.Path]) -> list[str]:
    """Return the public module-level constants that no module other than the one assigning them refers to."""
    return _module_local_names(files, _public_constants)


def _module_local_definitions(files: list[pathlib.Path]) -> list[str]:
    """Return the public module-level functions and classes that no module other than the defining one refers to."""
    return _module_local_names(files, _public_definitions)


def _module_local_names(
    files: list[pathlib.Path],
    public_names: Callable[[dict[pathlib.Path, ast.Module]], Iterator[tuple[pathlib.Path, str]]],
) -> list[str]:
    """Return the public names each module yields that no module other than the one defining them refers to.

    A name is taken to have an outside caller when another module imports it from the file defining it, reads it as
    an attribute, or names it in a string. The string counts because a name can be reached dynamically, through
    `getattr(module, "NAME")`, which a rename would break while leaving the string behind. Imports are matched by
    path rather than by module name, so the two `helpers.py` modules are told apart. Attributes and strings are
    matched by name alone, which can only hide a name, never invent one.
    """
    trees = {path: ast.parse(path.read_text()) for path in files}
    imported: set[tuple[str, str]] = set()
    mentioned: set[str] = set()
    for tree in trees.values():
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module and not node.level:
                module_file = node.module.replace(".", "/") + ".py"
                imported.update((module_file, alias.name) for alias in node.names)
            elif isinstance(node, ast.Attribute):
                mentioned.add(node.attr)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                mentioned.add(node.value)
    return sorted(
        f"{path}:{public_name}"
        for path, public_name in public_names(trees)
        if public_name not in mentioned
        and not any(path.as_posix().endswith(module_file) and public_name == name for module_file, name in imported)
    )


def _may_import_a_private(importer: pathlib.Path, module_file: str, files: list[pathlib.Path]) -> bool:
    """Return whether the importer may import a private name from the module, leaving it private.

    Three may: a module outside this project, whose privates are not ours to rename; a test of the very module
    defining it, which reads the code it covers from the inside; and any test importing from `src` or `tools`, for
    the same reason. Between two modules of the same kind the name is public in fact, whatever its spelling.
    """
    defining = [path for path in files if path.as_posix().endswith(module_file)]
    if not defining:
        return True
    if importer.name == f"test_{pathlib.PurePath(module_file).name}":
        return True
    return "tests" in importer.parts and any({"src", "tools"} & set(path.parts) for path in defining)


def _privates_imported_elsewhere(files: list[pathlib.Path]) -> list[str]:
    """Return the private module-level names another module imports, which makes them public in fact.

    The converse of the rules above: a name spelled with a leading underscore claims no caller outside its module,
    so an import elsewhere means the spelling and the fact have parted company.
    """
    reported: list[str] = []
    for path in files:
        for node in ast.walk(ast.parse(path.read_text())):
            if not isinstance(node, ast.ImportFrom) or not node.module or node.level:
                continue
            module_file = node.module.replace(".", "/") + ".py"
            if _may_import_a_private(path, module_file, files):
                continue
            reported += [f"{path}:{alias.name}" for alias in node.names if alias.name.startswith("_")]
    return sorted(reported)


class VisibilityTest(unittest.TestCase):
    """Test that a public module-level name has callers outside the module defining it.

    Constants, functions, and classes are all checked, bar the names reached without a call: a class a framework
    discovers, and the entry point a module runs when run as a script.
    """

    @staticmethod
    def reported(check: Callable[[list[pathlib.Path]], list[str]], files: dict[str, str]) -> list[str]:
        """Return the names the check reports for a project of the given files, without their paths."""
        with project(files) as directory:
            reported = check(sorted(pathlib.Path(directory).rglob("*.py")))
        return [entry.rsplit(":", maxsplit=1)[-1] for entry in reported]

    def test_private_names_have_no_importer_outside_their_module(self):
        """Test that a name kept private is imported nowhere else, so its spelling matches its callers."""
        self.assertEqual(_privates_imported_elsewhere(_python_files()), [])

    def test_a_private_name_imported_by_another_module_is_reported(self):
        """Test that a private name another module imports is reported, unless a test reaches into the code it tests."""
        files = {
            "src/pkg/mod.py": "_PRIVATE = 1\n",
            "tests/test_other.py": "from pkg.mod import _PRIVATE\n",  # a test reaching into the code it covers
            "tests/mutation.py": "_HARNESS = 2\n",
            "tests/test_mutation.py": "from tests.mutation import _HARNESS\n",  # a test of that very module
            "tests/outsider.py": "from unittest.mock import _Call\n",  # a private of another project
            "tests/helpers.py": "_HELPER = 3\n",
            "tests/test_architecture.py": "from tests.helpers import _HELPER\n",  # neither of those
        }
        self.assertEqual(self.reported(_privates_imported_elsewhere, files), ["_HELPER"])

    def test_constants_without_outside_callers_are_private(self):
        """Test that every public module-level constant is imported from its module or read as an attribute."""
        self.assertEqual(_module_local_constants(_python_files()), [])

    def test_definitions_without_outside_callers_are_private(self):
        """Test that every public module-level definition is imported from its module or read as an attribute."""
        self.assertEqual(_module_local_definitions(_python_files()), [])

    def test_constants_have_a_caller_outside_the_tests(self):
        """Test that no constant is public only so that a test can reach it.

        The `tools` scripts count as callers, so what they import stays public.
        """
        self.assertEqual(_module_local_constants([f for f in _python_files() if f.parts[0] != "tests"]), [])

    def test_a_constant_imported_from_another_root_is_not_reported(self):
        """Test that an import is matched to the module assigning it although the two sit under different roots."""
        files = {
            "one/pkg/mod.py": "SHARED = 1\nLOCAL = 2\n\nLOCAL\n",
            "two/importer.py": "from pkg.mod import SHARED\n\nSHARED\n",
        }
        self.assertEqual(self.reported(_module_local_constants, files), ["LOCAL"])

    def assert_only_the_unreached_constant_is_reported(self, reader: str) -> None:
        """Assert that of the two constants a module assigns, only the one the reader leaves alone is reported."""
        files = {"pkg/mod.py": "REACHED = 1\nUNREACHED = 2\n\nUNREACHED\n", "reader.py": reader}
        self.assertEqual(self.reported(_module_local_constants, files), ["UNREACHED"])

    def test_a_constant_named_in_a_string_is_not_reported(self):
        """Test that a constant another module names in a string is not reported, since it is reached that way."""
        self.assert_only_the_unreached_constant_is_reported('import pkg.mod\n\ngetattr(pkg.mod, "REACHED")\n')

    def test_a_constant_read_as_an_attribute_is_not_reported(self):
        """Test that a constant another module reads through the module object is not reported."""
        self.assert_only_the_unreached_constant_is_reported("import pkg.mod\n\npkg.mod.REACHED\n")

    def test_names_that_are_not_public_constants_are_not_reported(self):
        """Test that a function, a class, a lower-case variable, and an already-private constant are not reported."""
        source = "def function(): ...\nclass Klass: ...\nvariable = 1\n_PRIVATE = 2\nPUBLIC = 3\n"
        self.assertEqual(self.reported(_module_local_constants, {"mod.py": source}), ["PUBLIC"])

    def test_a_function_without_outside_callers_is_reported(self):
        """Test that a public module-level function no module other than the one defining it refers to is reported.

        An async function is a function here, so it is reported the same way.
        """
        files = {
            "pkg/mod.py": "def reached(): ...\ndef local(): ...\nasync def waited(): ...\n\nlocal()\n",
            "reader.py": "from pkg.mod import reached\n\nreached()\n",
        }
        self.assertEqual(self.reported(_module_local_definitions, files), ["local", "waited"])

    def test_a_test_case_is_not_reported(self):
        """Test that a class the test runner discovers is not reported, however far it sits from `TestCase`.

        A subscripted base names no class the scan can resolve, so a class carrying one is no test case.
        """
        direct = "import unittest\n\n\nclass Discovered(unittest.TestCase): ...\n"
        inherited = "import unittest\n\n\nclass Base(unittest.TestCase): ...\nclass Discovered(Base): ...\n"
        for case, source in {
            "direct": direct + "class Klass: ...\n",
            "inherited": inherited + "class Klass: ...\n",
            "subscripted base": direct + "class Klass(tuple[str, ...]): ...\n",
        }.items():
            with self.subTest(case=case):
                self.assertEqual(self.reported(_module_local_definitions, {"mod.py": source}), ["Klass"])

    def test_a_lint_rule_is_not_reported(self):
        """Test that a class the linter discovers is not reported."""
        source = "from fixit import LintRule\n\n\nclass Rule(LintRule): ...\nclass Klass: ...\n"
        self.assertEqual(self.reported(_module_local_definitions, {"mod.py": source}), ["Klass"])

    def test_an_entry_point_is_not_reported(self):
        """Test that the function a module runs when run as a script is not reported, unlike one merely named so.

        The name alone says nothing, since a module that never runs as a script exposes no entry point.
        """
        defined = "def main(): ...\ndef local(): ...\n"
        for case, source in {
            "entry point": defined + '\n\nif __name__ == "__main__":\n    main()\n',
            "named main only": defined,
        }.items():
            with self.subTest(case=case):
                expected = ["local"] if case == "entry point" else ["local", "main"]
                self.assertEqual(self.reported(_module_local_definitions, {"mod.py": source}), expected)
