"""Test the architecture of the tool."""

import ast
import contextlib
import inspect
import pathlib
import re
import tempfile
import unittest
from typing import TYPE_CHECKING

from archunitpython import assert_passes, project_files
from archunitpython.files.assertion import CustomFileViolation

from update_time.io.log import Logger

from tests.update_time import fixtures

if TYPE_CHECKING:
    from collections.abc import Generator, Iterator

    from archunitpython.files.assertion import CustomFileCondition, FileInfo

_MANIFEST_PARSERS = ("tomllib", "tomlkit", "yaml")

# What a file violating the settings rule did, named once so the rule and the test of the rule report it alike.
_READS_A_SETTING = "reads a setting the command line configures a run with"

# The layers, innermost rank first; the layers sharing a rank are siblings.
_RANKS = (
    ("primitives",),
    ("domain",),
    ("io",),
    ("file_formats", "sources"),
    ("package_managers", "references"),
    ("updaters",),
)
_LAYERS = tuple(layer for rank in _RANKS for layer in rank)


def _outer_layers(layer: str) -> tuple[str, ...]:
    """Return the layers the given layer may not use: its siblings, and everything further out."""
    rank = next(index for index, names in enumerate(_RANKS) if layer in names)
    siblings = tuple(name for name in _RANKS[rank] if name != layer)
    return siblings + tuple(name for names in _RANKS[rank + 1 :] for name in names)


def _module_pattern(module: str) -> re.Pattern[str]:
    """Return a pattern matching the module and its submodules.

    `matching()` reads a plain string as a glob, anchored to the whole module name recorded for an import, so `yaml`
    alone matches `import yaml` but not `from yaml.parser import Parser`. The glob `yaml*` would match the submodule,
    but also an unrelated distribution such as `yamllint`.
    """
    return re.compile(rf"{re.escape(module)}($|\.)")


def _package_init(package: str) -> str:
    """Return a path pattern matching the package's `__init__.py`.

    `from update_time.io import fetch` records a dependency on `io/__init__.py` rather than on `io/fetch.py`, so a
    rule naming the module alone never sees the import written that way. Forbidding the package as well closes that
    route, and leaves `from update_time.io.fetch import get` untouched, which records `io/fetch.py` as expected.
    The package is spelled as a path, `tests/update_time` rather than `tests.update_time`.
    """
    return f"*/{package}/__init__.py"


# Generated by `vulture --make-whitelist`: bare names rather than code, so what it mentions means nothing.
_GENERATED_FILES = ("tools/vulture-whitelist.py",)


def _python_files() -> list[pathlib.Path]:
    """Return the Python files the visibility check reads names and references from."""
    roots = ("src", "tests", "tools")
    files = (path for root in roots for path in pathlib.Path(root).rglob("*.py"))
    return sorted(path for path in files if path.as_posix() not in _GENERATED_FILES)


def _module_level_assignments(tree: ast.Module) -> Iterator[tuple[list[ast.expr], ast.expr | None]]:
    """Yield the targets and assigned value of each module-level assignment, annotated or not.

    An annotation without a value (`NAME: int`) assigns nothing, so its value is None.
    """
    for node in tree.body:
        if isinstance(node, ast.Assign):
            yield node.targets, node.value
        elif isinstance(node, ast.AnnAssign):
            yield [node.target], node.value


def _public_constants(tree: ast.Module) -> Iterator[str]:
    """Yield the public module-level constants the module assigns."""
    for targets, _value in _module_level_assignments(tree):
        for target in targets:
            if isinstance(target, ast.Name) and not target.id.startswith("_") and target.id.isupper():
                yield target.id


def _module_local_constants(files: list[pathlib.Path]) -> list[str]:
    """Return the public module-level constants that no module other than the one assigning them refers to.

    A constant is taken to have an outside caller when another module imports it from the file assigning it, reads
    it as an attribute, or names it in a string. The string counts because a constant can be reached dynamically,
    through `getattr(module, "NAME")`, which a rename would break while leaving the string behind. Imports are
    matched by path rather than by module name, so the two `helpers.py` modules are told apart. Attributes and
    strings are matched by name alone, which can only hide a constant, never invent one.
    """
    trees = {path: ast.parse(path.read_text()) for path in files}
    imported: set[tuple[str, str]] = set()
    mentioned: set[str] = set()
    for tree in trees.values():
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module and not node.level:
                module_file = node.module.replace(".", "/") + ".py"
                imported.update((module_file, alias.name) for alias in node.names)
            elif isinstance(node, ast.Attribute):
                mentioned.add(node.attr)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                mentioned.add(node.value)
    return sorted(
        f"{path}:{constant}"
        for path, tree in trees.items()
        for constant in _public_constants(tree)
        if constant not in mentioned
        and not any(path.as_posix().endswith(module_file) and constant == name for module_file, name in imported)
    )


def _env_var_globals(files: list[pathlib.Path]) -> set[str]:
    """Return the names assigned an `EnvVar`: the settings the command line configures a run with.

    Discovered rather than listed, so a setting added later is covered without this test being edited.
    """
    names: set[str] = set()
    for path in files:
        for targets, value in _module_level_assignments(ast.parse(path.read_text())):
            if isinstance(value, ast.Call) and isinstance(value.func, ast.Name) and value.func.id == "EnvVar":
                names.update(target.id for target in targets if isinstance(target, ast.Name))
    return names


def _reads_one_of(names: set[str]) -> CustomFileCondition:
    """Return a rule condition holding for a file that reads one of the names, by import or as an attribute.

    A condition rather than a rule of its own because archunitpython records a dependency on the module a name
    comes from, not on the name, and a source may use `cooldown.within_cooldown` while reading no setting.
    """

    def reads_one_of(file_info: FileInfo) -> bool:
        return any(
            (isinstance(node, ast.ImportFrom) and any(alias.name in names for alias in node.names))
            or (isinstance(node, ast.Attribute) and node.attr in names)
            for node in ast.walk(ast.parse(file_info.content))
        )

    return reads_one_of


@contextlib.contextmanager
def _project(files: dict[str, str]) -> Generator[str]:
    """Yield the path of a directory holding the given files, so a rule has a project to scan.

    The rules are exercised against a project written for the purpose, since the tree they normally scan holds no
    violation to find. Each key is a path relative to the directory, and the folders it names are created.
    """
    with tempfile.TemporaryDirectory() as directory:
        for name, source in files.items():
            path = pathlib.Path(directory) / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source)
        yield directory


class DependenciesTest(unittest.TestCase):
    """Unit test for module dependencies within the tool."""

    def test_no_cyclic_dependencies(self):
        """Test that there are no cyclic dependencies."""
        assert_passes(project_files("src/").should().have_no_cycles())

    def test_no_script_imports(self):
        """Test that scripts are not imported, by name or through the package holding them."""
        assert_passes(project_files("src/").should_not().depend_on_files().with_name("update_*.py"))
        assert_passes(project_files("src/").should_not().depend_on_files().in_path(_package_init("updaters")))

    def test_version_module_is_a_leaf(self):
        """Test that `version.py` depends on nothing else in `domain`, so the rest of `domain` can build on it.

        `version.py` holds the foundational types and helpers the rest of `domain` builds on: `bound.py` imports
        `is_valid` and the type aliases from it. So `version.py` must import nothing back from `domain`, making it a
        leaf within the layer. It may still build on the inner `primitives` layer, but not on its `domain` siblings.
        `have_no_cycles` forbids only a two-way dependency, not a one-way inversion, so pinning the direction here
        keeps `version.py` reasoned about and tested without the bound machinery.
        """
        rule = project_files("src/").with_name("version.py").should_not().depend_on_files().in_folder("domain")
        assert_passes(rule)


class TestSupportTest(unittest.TestCase):
    """Test the split between the two shared test modules.

    `fixtures.py` holds values the tests reuse and `helpers.py` holds behaviour — base test cases, builders,
    decorators — so a test looking for something reusable knows which of the two to read. Keeping the values free of
    behaviour is what lets `helpers.py` build on them without the dependency ever running the other way.
    """

    def test_fixtures_do_not_depend_on_helpers(self):
        """Test that fixtures.py doesn't import helpers.py, so the dependency only runs from helpers to fixtures."""
        fixtures_file = project_files("tests/").with_name("fixtures.py")
        assert_passes(fixtures_file.should_not().depend_on_files().with_name("helpers.py"))
        assert_passes(fixtures_file.should_not().depend_on_files().in_path(_package_init("tests/update_time")))

    def test_fixtures_define_no_behaviour(self):
        """Test that fixtures.py defines no function or class, so behaviour is only ever added to helpers.py."""
        defined_here = [
            name
            for name, value in vars(fixtures).items()
            if (inspect.isfunction(value) or inspect.isclass(value)) and value.__module__ == fixtures.__name__
        ]
        self.assertEqual(defined_here, [])


class LayeringTest(unittest.TestCase):
    """Test the layered architecture, which `_RANKS` declares innermost to outermost.

    A layer may use the ones before it. It may use neither a sibling sharing its rank nor a layer after it:
    - `primitives` are project-agnostic building blocks, like a typed environment variable, that even the pure core may
      reach for.
    - `domain` is the pure, I/O-free core.
    - `io` wraps file, process, and log I/O.
    - `file_formats` read, write, and parse specific manifest formats.
    - `sources` are the registry and API clients.
    - `package_managers` drive the external managers, uv, npm, and pnpm, using file_formats and sources.
    - `references` decide which version a pinned reference should update to, and rewrite the reference accordingly.
    - `updaters` wire everything together.

    Keeping the arrows pointing one way is what lets `domain` be tested in isolation and `file_formats` and `sources`
    be reused.
    """

    def test_no_layer_uses_an_outer_layer(self):
        """Test that no layer depends on a sibling of it or on a layer further out.

        Every layer is taken from the ranks rather than named here, so one added to them is covered by this rule
        without anyone having to remember to cover it.
        """
        for layer in _LAYERS:
            for outer_layer in _outer_layers(layer):
                with self.subTest(layer=layer, outer_layer=outer_layer):
                    rule = project_files("src/").in_folder(layer).should_not().depend_on_files().in_folder(outer_layer)
                    assert_passes(rule)

    def test_every_folder_a_rule_names_is_a_layer(self):
        """Test that each folder name spelled out in a rule is a layer.

        The names are read out of this module rather than declared here, so a rule scoped to a mistyped folder is
        caught whether or not whoever wrote it thought about the check.
        """
        tree = ast.parse(pathlib.Path(__file__).read_text())
        named = [
            node.args[0].value
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "in_folder"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ]
        self.assertNotEqual(named, [])  # An empty list would pass the check below without checking anything.
        self.assertEqual([name for name in named if name not in _LAYERS], [])

    def test_the_layers_are_the_folders(self):
        """Test that every layer named here is a folder, and every folder under the package is a layer.

        A layer whose folder was renamed would leave its rules selecting nothing, and a folder added without a layer
        to match would go unmentioned by any rule at all.
        """
        folders = [path.name for path in pathlib.Path("src/update_time").iterdir() if path.is_dir()]
        self.assertEqual(sorted(name for name in folders if not name.startswith("__")), sorted(_LAYERS))

    def test_network_access_goes_through_io(self):
        """Test that only the io layer touches the network directly.

        Every other layer reaches the network through `io.fetch`, never by importing `requests` or a submodule of it,
        so all HTTP goes through one place with a uniform timeout, error handling, and logging. This also keeps the
        pure domain layer free of any I/O.
        """
        for layer in (name for name in _LAYERS if name not in ("io", "file_formats")):
            with self.subTest(layer=layer):
                rule = project_files("src/").in_folder(layer).should_not().depend_on_external_modules()
                assert_passes(rule.matching(_module_pattern("requests")))

    def test_registry_access_goes_through_sources(self):
        """Test that updaters reach registries through the sources layer, never fetching from them directly.

        `sources` own every registry/API client, so an updater fetches nothing itself: it wires a source's
        `get_latest_*` to the file-rewriting machinery. Keeping the HTTP in `sources` is what lets a single client
        be reused across updaters and keeps updaters as thin as each other.
        """
        updaters = project_files("src/").in_folder("updaters")
        assert_passes(updaters.should_not().depend_on_files().with_name("fetch.py"))
        assert_passes(updaters.should_not().depend_on_files().in_path(_package_init("io")))

    def test_manifest_parsing_goes_through_file_formats(self):
        """Test that reading/writing manifest files is confined to the file_formats layer.

        `file_formats` owns the manifest formats, so the parsers only it needs (`tomllib`/`tomlkit` for TOML, `yaml`
        for YAML) are manifest-only and no other layer imports them. `json` is not confined the same way — `io.process`
        parses JSON *command output* (`npm`/`pnpm --json`), which is not a manifest — but no updater parses a manifest
        itself: it goes through file_formats. So updaters import none of the four.
        """
        for layer in (name for name in _LAYERS if name != "file_formats"):
            for module in _MANIFEST_PARSERS:
                with self.subTest(layer=layer, module=module):
                    rule = project_files("src/").in_folder(layer).should_not().depend_on_external_modules()
                    assert_passes(rule.matching(_module_pattern(module)))
        for module in ("json", *_MANIFEST_PARSERS):
            with self.subTest(layer="updaters", module=module):
                rule = project_files("src/").in_folder("updaters").should_not().depend_on_external_modules()
                assert_passes(rule.matching(_module_pattern(module)))


class ConfigurationReadingTest(unittest.TestCase):
    """Test that a module which decides nothing about a run's configuration is told it rather than reading it.

    Every setting a source honours — the cooldown, and any added later — reaches it as an argument of the
    `NewVersionGetter` contract, decided once by `references.resolve.latest_version`. A source reading the global
    itself would answer with the run's setting where the caller asked for another, which is what a per-reference
    override needs the source not to do. The marker parser is held to the same rule, for the reason its own test
    gives.
    """

    def test_sources_read_no_configuration_global(self):
        """Test that no source reads a setting, and that there are settings to be read.

        The settings are discovered from `src` alone, since the tests declare `EnvVar`s of their own to exercise the
        class, and those are not settings a run is configured with.
        """
        settings = _env_var_globals(sorted(pathlib.Path("src").rglob("*.py")))
        self.assertIn("COOLDOWN", settings)  # Assert the settings were found, so an empty scan can't pass silently.
        sources = project_files("src/").in_folder("sources")
        assert_passes(sources.should_not().adhere_to(_reads_one_of(settings), _READS_A_SETTING))

    def test_the_marker_parser_reads_no_configuration_global(self):
        """Test that the marker parser reads no setting, so a marker means the same whatever a run is configured with.

        `marker.py` imports `RISK_LEVELS` from the module that also defines `WARN_VULNERABILITY_LEVEL`, which puts a
        setting one import away. Reading it while parsing would decide there whether a marker beats the command line,
        where `Threshold.value_or` decides it once for whichever check asks.
        """
        settings = _env_var_globals(sorted(pathlib.Path("src").rglob("*.py")))
        self.assertIn("COOLDOWN", settings)  # Assert the settings were found, so an empty scan can't pass silently.
        marker_parser = project_files("src/").with_name("marker.py")
        assert_passes(marker_parser.should_not().adhere_to(_reads_one_of(settings), _READS_A_SETTING))

    def test_a_module_reading_a_setting_is_reported(self):
        """Test that a module is reported whether it imports the setting or reads it off its module.

        Without this the rule above would pass just as well when the condition found nothing whatever a source does.
        """
        files = {
            "settings.py": "SETTING = EnvVar('X')\n",
            "importer.py": "from settings import SETTING\n",
            "attribute.py": "import settings\n\nsettings.SETTING.get()\n",
            "reader.py": "from settings import read_setting\n",
        }
        with _project(files) as directory:
            settings = _env_var_globals(sorted(pathlib.Path(directory).rglob("*.py")))
            rule = project_files(directory).should_not().adhere_to(_reads_one_of(settings), _READS_A_SETTING)
            violations = [violation for violation in rule.check() if isinstance(violation, CustomFileViolation)]
            reported = sorted(pathlib.Path(violation.file_info.path).name for violation in violations)
        self.assertEqual(reported, ["attribute.py", "importer.py"])


class ToolInvocationTest(unittest.TestCase):
    """Test that the tools are run as modules rather than as scripts.

    Running `python tools/thing.py` puts `tools` itself on the import path, where the package by that name can't be
    found, so the script dies on its first `from tools...` import. The tests import the tools as a package and so
    never meet it, which leaves the recipe running them as the only place it shows.
    """

    def test_tools_are_run_as_modules(self):
        """Test that no recipe runs a tool as a script, reporting the recipe lines that do."""
        lines = pathlib.Path("justfile").read_text().splitlines()
        self.assertEqual([line.strip() for line in lines if "python tools/" in line], [])


class SubmoduleImportTest(unittest.TestCase):
    """Test that the rules naming an external module see the submodule form this project imports them in.

    This project imports external modules by submodule throughout, `from packaging.version import Version` for
    example, so a submodule is the likelier form in which a violation would arrive.
    """

    def assert_reports_submodule_import(self, module: str) -> None:
        """Assert that the module's pattern reports a file that imports a submodule of the module."""
        with _project({"importer.py": f"from {module}.sub import thing\n"}) as directory:
            rule = project_files(directory).should_not().depend_on_external_modules()
            self.assertEqual(len(rule.matching(_module_pattern(module)).check()), 1)

    def test_network_access_rule_reports_a_submodule_import(self):
        """Test that the rule confining network access to io reports a `requests` submodule import."""
        self.assert_reports_submodule_import("requests")

    def test_manifest_parsing_rule_reports_a_submodule_import(self):
        """Test that the rule confining manifest parsing to file_formats reports a parser's submodule import."""
        for module in ("json", *_MANIFEST_PARSERS):
            with self.subTest(module=module):
                self.assert_reports_submodule_import(module)


class PackageImportTest(unittest.TestCase):
    """Test that the pattern forbidding a package matches the `__init__.py` a package-form import records.

    The rules that name a module lean on this pattern to cover the import written as `from update_time.io import
    fetch`. A pattern matching nothing would leave those rules passing whatever the code does, and every one of
    them would keep passing, so nothing else in the suite would reveal it.
    """

    def test_pattern_reports_a_package_import(self):
        """Test that the pattern reports the import written through the package, and not the one naming the module."""
        files = {
            "pkg/__init__.py": "",
            "pkg/target.py": "thing = 1\n",
            "package_form.py": "from pkg import target\n\ntarget\n",
            "module_form.py": "from pkg.target import thing\n\nthing\n",
        }
        with _project(files) as directory:
            rule = project_files(directory).should_not().depend_on_files().in_path(_package_init("pkg"))
            self.assertEqual(len(rule.check()), 1)


class VisibilityTest(unittest.TestCase):
    """Test that a public module-level constant has callers outside the module assigning it.

    A name without a leading underscore claims such callers, and the claim goes stale silently, since nothing fails
    when the last one goes away. Constants are checked here; a function or class discovered by a framework rather
    than imported, a `TestCase` subclass or a fixit rule, has no caller to find and would be reported wrongly.
    """

    @staticmethod
    def reported(files: dict[str, str]) -> list[str]:
        """Return the constants the check reports for a project of the given files, without their paths."""
        with _project(files) as directory:
            reported = _module_local_constants(sorted(pathlib.Path(directory).rglob("*.py")))
        return [entry.rsplit(":", maxsplit=1)[-1] for entry in reported]

    def test_constants_without_outside_callers_are_private(self):
        """Test that every public module-level constant is imported from its module or read as an attribute."""
        self.assertEqual(_module_local_constants(_python_files()), [])

    def test_constants_have_a_caller_outside_the_tests(self):
        """Test that no constant is public only so that a test can reach it.

        A constant the tests alone import is public for their benefit, which widens what the module offers without
        anything outside the tests asking for it. Leaving the tests out of the scan is what surfaces those, since
        the constant then has no caller left. The `tools` scripts count as callers, so what they import stays public.
        """
        self.assertEqual(_module_local_constants([f for f in _python_files() if f.parts[0] != "tests"]), [])

    def test_a_constant_imported_from_another_root_is_not_reported(self):
        """Test that an import is matched to the module assigning it although the two sit under different roots.

        The importer names `pkg.mod`, while the module assigning the constant sits at `one/pkg/mod.py`, as `src`
        prefixes the package in this project. Matching the tail of the path is what ties the two together.
        """
        files = {
            "one/pkg/mod.py": "SHARED = 1\nLOCAL = 2\n\nLOCAL\n",
            "two/importer.py": "from pkg.mod import SHARED\n\nSHARED\n",
        }
        self.assertEqual(self.reported(files), ["LOCAL"])

    def assert_only_the_unreached_constant_is_reported(self, reader: str) -> None:
        """Assert that of the two constants a module assigns, only the one the reader leaves alone is reported."""
        files = {"pkg/mod.py": "REACHED = 1\nUNREACHED = 2\n\nUNREACHED\n", "reader.py": reader}
        self.assertEqual(self.reported(files), ["UNREACHED"])

    def test_a_constant_named_in_a_string_is_not_reported(self):
        """Test that a constant another module names in a string is not reported, since it is reached that way.

        A module's constant can be read through `getattr` rather than imported. Reporting it would call for a rename
        that breaks the reader, because the name it looks up is spelled in a string the rename leaves behind.
        """
        self.assert_only_the_unreached_constant_is_reported('import pkg.mod\n\ngetattr(pkg.mod, "REACHED")\n')

    def test_a_constant_read_as_an_attribute_is_not_reported(self):
        """Test that a constant another module reads through the module object is not reported.

        Importing the module rather than the constant reaches it just as well, so the constant has a caller even
        though no `from ... import` names it.
        """
        self.assert_only_the_unreached_constant_is_reported("import pkg.mod\n\npkg.mod.REACHED\n")

    def test_names_that_are_not_public_constants_are_not_reported(self):
        """Test that a function, a class, a lower-case variable, and an already-private constant are not reported."""
        source = "def function(): ...\nclass Klass: ...\nvariable = 1\n_PRIVATE = 2\nPUBLIC = 3\n"
        self.assertEqual(self.reported({"mod.py": source}), ["PUBLIC"])


class PackageImportBlindSpotTest(unittest.TestCase):
    """Test that a rule naming a module still misses the import written through the package.

    This pins what archunitpython records rather than anything this project decides, so that an upgrade changing it
    is noticed. Were a later version to record `pkg/target.py` for `from pkg import target`, this test would fail,
    and the companion assertions naming the package in the rules above could be dropped.
    """

    def test_a_package_import_is_not_recorded_against_the_module(self):
        """Test that naming the module reports nothing, while naming the package reports the very same import.

        The alias is a case of its own, since a module renamed on import is how several of this project's own
        package imports are written.
        """
        for importer in ("from pkg import target\n\ntarget\n", "from pkg import target as alias\n\nalias\n"):
            with self.subTest(importer=importer.splitlines()[0]):
                files = {"pkg/__init__.py": "", "pkg/target.py": "thing = 1\n", "importer.py": importer}
                with _project(files) as directory:
                    by_module = project_files(directory).should_not().depend_on_files().with_name("target.py")
                    by_package = project_files(directory).should_not().depend_on_files().in_path(_package_init("pkg"))
                    self.assertEqual(by_module.check(), [])
                    self.assertEqual(len(by_package.check()), 1)


class LoggerMessageTest(unittest.TestCase):
    """Test that Logger's message templates and its log methods pair one-to-one.

    Each `MESSAGE_` template on `Logger` belongs to the log method that emits it, but the class layout can only
    express that by convention (each template sits directly above its method), so the pairing is checked here by
    inspecting which templates each method references.
    """

    @staticmethod
    def methods_by_template() -> dict[str, set[str]]:
        """Return, for each message template on Logger, the names of the log methods that reference it."""
        templates = {name for name in vars(Logger) if name.removeprefix("_").startswith("MESSAGE_")}
        references: dict[str, set[str]] = {template: set() for template in templates}
        for name in vars(Logger):
            if name.startswith("__") or not inspect.isfunction(function := getattr(Logger, name)):
                continue
            for template in templates & set(function.__code__.co_names):
                references[template].add(name)
        return references

    def test_each_template_belongs_to_exactly_one_method(self):
        """Test that each message template is referenced by exactly one log method: no orphans, no sharing."""
        unpaired = {template: methods for template, methods in self.methods_by_template().items() if len(methods) != 1}
        self.assertEqual(unpaired, {})

    def test_each_method_references_at_most_one_template(self):
        """Test that no log method references more than one message template."""
        template_counts: dict[str, int] = {}
        for methods in self.methods_by_template().values():
            for method in methods:
                template_counts[method] = template_counts.get(method, 0) + 1
        self.assertEqual({method: count for method, count in template_counts.items() if count > 1}, {})
