"""requirements.txt updater script bumps exact-pinned dependencies to their latest PyPI versions.

Only hand-written, exact pins (`package==version`) are updated; looser specifiers (`>=`, `~=`, `<=`,
ranges and unpinned names) are left untouched, so a `<=` cap remains the way to opt a dependency out. Extras,
environment markers and inline comments on a line are preserved because only the version substring is replaced.

Compiled or locked files are left completely untouched: bumping a single `==` in them without recompiling the
transitive pins (and hashes) would corrupt the file. A requirements file is treated as compiled when it carries
`--hash=` lines (pip requires every requirement to be hashed, so the file is fully locked), an autogenerated
header from pip-compile or uv, or a sibling `.in` source file.
"""

import re
import sys
from typing import TYPE_CHECKING

from update_time.io.filesystem import glob, update_file
from update_time.io.log import get_logger
from update_time.sources.pypi import get_latest_version

if TYPE_CHECKING:
    from pathlib import Path

LOG = get_logger("requirements.txt")
# Match an exact pin at the start of a line: an optionally-extra'd package name followed by `==` and a version.
# `===` (arbitrary equality) and other operators don't match, so only `==` pins are updated.
REQUIREMENT_RE = (
    r"^(?P<dependency>[A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?\s*==\s*(?P<version>[A-Za-z0-9][A-Za-z0-9._!+-]*)"
)
AUTOGENERATED_RE = re.compile(r"autogenerated by (pip-compile|uv)")


def is_compiled(requirements_txt: Path, contents: str) -> bool:
    """Return whether the requirements file is compiled or locked and must be left untouched."""
    if "--hash=" in contents:
        return True  # pip requires every requirement to be hashed, so the file is fully locked
    if AUTOGENERATED_RE.search(contents):
        return True  # generated by pip-compile or `uv pip compile`
    return (requirements_txt.parent / f"{requirements_txt.stem}.in").exists()  # a sibling .in means it's generated


def update_requirements_txt(requirements_txt: Path) -> int:
    """Update the exact pins in a single requirements file, unless it is compiled or locked."""
    if is_compiled(requirements_txt, requirements_txt.read_text()):
        LOG.skipped(requirements_txt, "compiled or hash-pinned requirements file")
        return 0
    return update_file(requirements_txt, REQUIREMENT_RE, get_latest_version, LOG)


def update_requirements_txts() -> int:
    """Find all requirements files and update the exact pins in them."""
    requirements_files = set(glob("requirements*.txt")) | set(glob("requirements/*.txt"))
    results = {update_requirements_txt(requirements_txt) for requirements_txt in requirements_files}
    return max(results, default=0)


if __name__ == "__main__":  # pragma: no cover
    sys.exit(update_requirements_txts())
