"""Unit tests for the requirements.txt file format, with file I/O mocked."""

import unittest

from update_time.manifests import requirements_txt

from tests.update_time.helpers import requirements_file


class IsCompiledTest(unittest.TestCase):
    """Unit tests for detecting compiled/locked requirements files."""

    def test_hash_pinned(self):
        """Test that a hash-pinned (fully locked) file is compiled."""
        self.assertTrue(requirements_txt.is_compiled(requirements_file("flask==1.0 \\\n    --hash=sha256:abc\n")))

    def test_autogenerated_header(self):
        """Test that a pip-compile/uv autogenerated header marks the file as compiled."""
        self.assertTrue(requirements_txt.is_compiled(requirements_file("# autogenerated by pip-compile\nflask==1.0\n")))

    def test_sibling_in_file(self):
        """Test that a sibling .in source file marks the file as compiled."""
        self.assertTrue(requirements_txt.is_compiled(requirements_file("flask==1.0\n", sibling_in=True)))

    def test_plain_requirements(self):
        """Test that a plain hand-written requirements file is not compiled."""
        self.assertFalse(requirements_txt.is_compiled(requirements_file("flask==1.0\n")))
